<?php require_once '../../template/header.php'; ?><script>document.title = 'දැනුමිණ | ප්‍රකට චරිත';document.querySelector('[data-class=heading]').textContent = 'හොලිවුඩ් සිනෙමාවේ විනෝදාස්වාදයේ රජු ස්ටීවන් ස්පීල්බර්ග් - දෙවන කොටස';document.querySelector('.prev-article-btn').lastElementChild.innerText = 'ජෛවගෝලය';document.querySelector('.next-article-btn').firstElementChild.innerText = 'පුදුම හිතෙන තැන්';document.querySelector('.prev-article-btn').setAttribute('href','./biology.php');document.querySelector('.next-article-btn').setAttribute('href','./places.php');</script><p class='has-text-justified'>1990න් පසු ස්පීල්බර්ග්ගේ දෙවන චිත්‍රපටිය 1993 වසරේ තිරගත වූ ශින්ඩ්ලර්ස් ලිස්ට් (Schindler’s List), දෙවන ලෝක යුධ සමයේ පෝලන්ත යුදෙව්වන්, නාසි වධ කඳවුරුවලට ගෙනයාම වැළකීමට ජර්මානු කර්මාන්තකරුවෙකු වූ ඔස්කාර් ශින්ඩ්ලර් දරන උත්සාහය පෙන්වන කළු සුදු චිත්‍රපටයකි. </p><div class='columns'><div class='column is-6'><figure><img src='./images/biography/1.jpg'><figcaption>ස්පීල්බර්ග්, ශින්ඩ්ලර්ස් ලිස්ට් චිත්‍රපටියේ ප්‍රධාන නළු ලියාම් නීසන් සමඟ</figcaption></figure></div><div class='column is-6'><figure><img src='./images/biography/7.jpg'><figcaption>ස්පීල්බර්ග්, ශින්ඩ්ලර්ස් ලිස්ට් චිත්‍රපටියේ ප්‍රධාන නළු ලියාම් නීසන් සමඟ</figcaption></figure></div></div><p class='has-text-justified'>මෙම අති විශිෂ්ට සිනෙමා නිර්මාණය, හොඳම අධ්‍යක්‍ෂකවරයා සඳහාවූ ස්පීල්බර්ග්ගේ පළමු ඇකඩමි සම්මානය හිමි කර දුන්නේය. නළු ලියාම් නීසන්, බෙන් කිංස්ලි හා රැල්ෆ් ෆියනෙස්ගේ අති විශිෂ්ට රංගනය නිසාම විශිෂ්ටතම සිනෙමා නිර්මාණය ඇතුළුව ඔස්කාර් සම්මාන 6ක්  දිනා ගත්තේය. </p><div class='columns'><div class='column is-8'><p class='has-text-justified'>ස්පීල්බර්ග් 1994 වසරේදී,  ජෙෆ්රි කැට්සන්බර්ග් සහ ඩේවිඩ් ජෙෆෙන් හා එක්ව නව ස්ටුඩියෝවක් ඇරඹීය. ඒ අනුව සුප්‍රසිද්ධ ඩ්‍රීම්වර්ක්ස් (DreamWorks) ආයතනය බිහිවිය.  අතිශය සාර්ථක වූ සජීවිකරණ නිර්මාණ කිහිපයක්ම නව ස්ටුඩියෝව හරහා ප්‍රේක්ෂකයාට ගෙන එන්නට ඔහු සමත් විය. 
ඈන්ට්ස් (1998), ශ්රේක් චිත්‍රපට මාලාව, පූස් ඉන් බූට්ස් එලෙස බිහිවූ නිර්මාණ කිහිපයකි. 
</p><p class='has-text-justified'>The Lost World: Jurassic Park (1997), ජුරාසික් පාක්  ද ලොස්ට් වර්ල්ඩ්,  ස්පීල්බර්ග්ගේ මීළඟ ජුරාසික් පාක් චිත්‍රපටය විය. එය ජුරාසික් පාක් පළමු චිත්‍රපටය තරම් ප්‍රේක්ෂකයින් අතරට නොගිය මුත් සාර්ථක චිත්‍රපටයක් විය. 
</p><p class='has-text-justified'>ස්පීල්බර්ග්ගේ මීළඟ චිත්‍රපටය අමිස්ටඩ් - Amistad නමින් 1997 වසරේ තිරගත විය. එය ස්පීල්බර්ග්ට විශේෂ  වුයේ ඔහු සමාජ ඉතිහාසඥයෙකුගේ කාර්යයට පිවිසීම නිසායි. 
</p></div><div class='column is-4'><figure><img src='./images/biography/3.jpg'><figcaption>ඩ්‍රීම් වර්ක්ස් ස්ටුඩියෝවෙන් බිහිවූ සුප්‍රසිද්ධ සජීවීකරණ(Animation) නිර්මාණ </figcaption></figure></div></div><p class='has-text-justified'>1839 දී ස්පාඤ්ඤ වහල් නෞකාවක් වූ අමිස්ටඩ් (Amistad) නැවෙහි සිදු වූ වහල් කැරැල්ල වටා ගෙතුණු මෙම චිත්‍රපටයේ සුපිරි නළු මැතිව් මැක්කොනේ (Matthew McConaughey) නීතීඥයෙකු ලෙස අති විශිෂ්ට රංගනයක නිරත විය. 
හිටපු එක්සත් ජනපද ජනාධිපති ජෝන් ක්වින්සි ඇඩම්ස් ගේ චරිතයට පණදුන් ඇන්තනි හොප්කින්ස් ඇකඩමි සම්මාන සඳහාද යෝජනා විය. 
</p><div class='columns'><div class='column is-4'><figure><img src='./images/biography/2.jpg'><figcaption>ජුරාසික් පාර්ක් පළමු චිත්‍රපටිය වෙනුවෙන්, නිමැවු විශාල ටී රෙක්ස් ඩයිනසෝර් මුර්තිය</figcaption></figure></div><div class='column is-4'><figure><img src='./images/biography/2b.jpg'><figcaption> ස්ටෑන් වින්ස්ටන් ස්ටුඩියෝවේ ප්‍රධාන මුර්තිකරු මයික් ටර්සික්</figcaption></figure></div><div class='column is-4'><figure><img src='./images/biography/4b.jpg'><figcaption>අමිස්ටඩ් - Amistad චිත්‍රපටියේ දර්ශන හා රූගත කිරීම් </figcaption></figure></div></div><div class='columns'><div class='column is-8'><p class='has-text-justified'>1998 වසරේ තිරගත වූ දෙවන ලෝක යුධ සමය නිරූපණය කරන සේවින්ග් ප්‍රයිවට් රයන් - Saving Private Ryan, ස්පීල්බර්ග්ගේ මීළඟ අති සාර්ථක සිනෙමා කෘතියයි.  
හොඳම චිත්‍රපටය ඇතුළුව ඇකඩමි සම්මාන 11ක් සඳහා නිර්දේශ වූ මෙය හොඳම අධ්‍යක්ෂවරයා ලෙස ඔහුගේ දෙවන ඇකඩමි සම්මානය දිනා දුන්නේය. 
මෙම චිත්‍රපටය එම වසරේ ඇමරිකා එක්සත් ජනපදයේ තිරගත වූ ඉහළම වාණිජමය වශයෙන් සාර්ථකවූ චිත්‍රපටයයි. 
</p><p class='has-text-justified'>ස්පීල්බර්ග් 21 වන සියවස අරඹන්නේ විද්‍යා ප්‍රබන්ධ සිනෙමා කෘති දෙකකිනි. 
ඉන් පළමුවැන්න ලොව පුරා රසිකයින්ගේ හදවත් දිනු, A.I. හෙවත්, දි ආර්ටිෆිෂල් ඉන්ටෙලිජන්ස් - A.I. Artificial Intelligence (2001) නම් වූ දැවැන්ත සිනෙමා නිර්මාණයයි.
දෙවැන්න වුයේ 2002 වසරේ තිරගතවූ, සුපිරි නළු, ටොම් කෘස් ප්‍රධාන චරිතයට රඟපෑ මයිනරිටි රිපෝර්ට් - Minority Report චිත්‍රපටයයි. 
</p><p class='has-text-justified'>2004 වසරේ තිරගත වූ ස්පීල්බර්ග්ගේ මීළඟ චිත්‍රපටය The Terminal නම් විය. ප්‍රංශයේ චාල්ස් ඩි ගෝල් ගුවන් තොටුපළේ වසර 17ක් අතරමංව සිටි මිනිසකු වටා ගෙතුණු සත්‍ය සිදුවීමක් පාදක කරගත් මෙම චිත්‍රපටයේ ප්‍රධාන චරිතය රඟපෑවේ ටොම් හෑන්ක්ස් විසිනි. 
එහෙත් එම චිත්‍රපටය වාණිජමය වශයෙන් ස්පීල්බර්ග්ගේ අසාර්ථකම චිත්‍රපටි වලින් එකකි. </p><p class='has-text-justified'>ඉන් නොනැවතුණු ස්පීල්බර්ග්ගේ මීළඟ සිනෙමා නිර්මාණය, War of the Worlds විද්‍යා ප්‍රබන්ධ චිත්‍රපටිය, බොක්ස් ඔෆීස් වාර්තා තැබූ, අති සාර්ථක චිත්‍රපටයක් විය. එහි ප්‍රධාන නළුවා ලෙස ටොම් කෘස් නැවතත් එක් විය. එය 2005 වසරේ තිරගත විය. 
</p></div><div class='column is-4'><figure><img src='./images/biography/5c.jpg'><figcaption>සේවින්ග් ප්‍රයිවට් රයන් - Saving Private Ryan චිත්‍රපටියේ රූගත කිරීම් අතරතුර, එහි ප්‍රධාන නළු, ටොම් හෑන්ක්ස් සමඟ  </figcaption></figure></div></div><div class='columns'><div class='column is-4'><figure><img src='./images/biography/8.jpg'><figcaption>1993 වසරේ තිරගතවූ ජුරාසික් පාර්ක් චිත්‍රපටයේ දර්ශනයක් </figcaption></figure></div><div class='column is-4'><figure><img src='./images/biography/6.jpg'><figcaption>AI චිත්‍රපටියේ, කෘතීම බුද්ධිය සහිත රොබෝ දරුවාට රඟපෑ හේලි ජොයෙල් ඔස්මන්ට්.</figcaption></figure></div><div class='column is-4'><figure><img src='./images/biography/14.jpg'><figcaption>සුපිරි නළු ටොම් කෘස්, War of the Worlds චිත්‍රපටයේ </figcaption></figure></div></div><p class='has-text-justified'>එම වසරේම ඔහු විසින් නිර්මාණය කරන ලද Munich - මියුනිච් චිත්‍රපටය, හොඳම චිත්‍රපටිය හා හොඳම අධ්‍යක්ෂකවරයා සඳහා වූ ඇකඩමි සම්මාන සඳහා නිර්දේශ විය. සුපිරි ජේම්ස් බොන්ඩ් නළු ඩැනියෙල් ක්‍රේග් රඟපෑ මෙම චිත්‍රපටිය, 
1972 වසරේ මියුනිච් ඔලිම්පික් උළෙලේ ඊශ්‍රායල ඔලිම්පික් කණ්ඩායමේ 11 දෙනෙකු ඝාතනය කෙරූ පලස්තීන ත්‍රස්තවාදීන් අල්ලා ගැනීමේ මෙහෙයුමක් සම්බන්ධයෙන් නිර්මාණය විණි.</p><div class='columns'><div class='column is-7'><p class='has-text-justified'>වසර 19 කට පසුව නැවතත් ඉන්ඩියානා ජෝන්ස් චිත්‍රපටයක් නිර්මාණය කිරීම ස්පිල්බර්ග්ගේ මීළඟ අභිප්‍රාය විය. 
ඒ අනුව ඉන්ඩියානා ජෝන්ස් සහ කිංග්ඩම් ඔෆ් ද ක්‍රිස්ටල් ස්කල් - Indiana Jones and the Kingdom of the Crystal Skull 2008 වසරේදී නිර්මාණය විණි. 
ඒ වනවිට වයස අවුරුදු 64ක් වූ හැරිසන් ෆෝඩ් මෙවරත් වික්‍රමාන්විත දක්වන මහාචාර්යවරයා ලෙස ඔහුගේ භූමිකාව නිරූපණය කළේය. </p><figure><img src='./images/biography/9.jpg'><figcaption>ටොම් හෑන්ක්ස් The Terminal චිත්‍රපටයේ</figcaption></figure></div><div class='column is-5'><figure><img src='./images/biography/10.jpg'><figcaption>64 වියැති නළු, හැරිසන් ෆෝර්ඩ්, ඉන්දියානා ජෝන්ස් ලෙසින්</figcaption></figure></div></div><div class='columns'><div class='column is-4'><figure><img src='./images/biography/16.jpg'><figcaption>The Adventures of Tintin චිත්‍රපටිය (2011)</figcaption></figure></div><div class='column is-8'><p class='has-text-justified'>වසර තුනක පමණ විවේකයකට පසුව, ස්පීල්බර්ග්, සජීවීකරණ චිත්‍රපටියක් නිර්මාණය කළේය. ලෝකප්‍රසිද්ධ ලෝර්ඩ් ඔෆ් ද රින්ග්ස් කථා මාලාවේ අධ්‍යක්‍ෂක, පීටර් ජැක්සන් මෙවර ඔහුගේ නිෂ්පාදකයා විය. 
ඒ වනවිට අතිශය ජනප්‍රියව තිබුණු ටින් ටින් කාටුන් කථා මාලාව, The Adventures of Tintin නමින් 2011 වසරේදී සජීවීකරණ චිත්‍රපටයක් බවට පත් විය. ලෝර්ඩ් ඔෆ් ද රින්ග්ස් කථා මාලාවේ එන ගොලම්(Gollum) චරිතය නිර්මාණය සඳහා යොදාගත් සජීවීකරණ තාක්ශණයම මෙම චිත්‍රපටයට යොදාගැනිණි. 
ටින් ටින් කාටුනයේ රසිකයින්ගෙන් විවිධ විවේචන එල්ල වුවත්, චිත්‍රපටිය බොක්ස් ඔෆීස් වාර්තා තැබීය.
</p><p class='has-text-justified'>2012 දී ටෝනි කුෂ්නර්ගේ තිර රචනයක්වූ ලින්කන් - Lincoln චිත්‍රපටිය ස්පීල්බර්ග් අතින් නිමැවිණි. 
ඒබ්‍රහම් ලින්කන් ජනාධිපතිවරයා යටතේ ගෙන ආ 13වන ව්‍යවස්ථා සංශෝධනය මඟින් වහල් වෙළඳාම අහෝසි කිරීමේ මතභේදාත්මක තීන්දුව වටා ගෙතුණු මෙම කථාව හොඳම චිත්‍රපටය සහ අධ්‍යක්ෂණය ඇතුළුව ඔස්කාර් සම්මාන 12ක් හිමි කරගත්තේය. 
ලින්කන් ජනපතිවරයා ලෙස ප්‍රධාන චරිතයට පණ දුන්නේ ඩැනියෙල් ඩේ-ලුවිස්ය.
</p></div></div><p class='has-text-justified'>ඉන්පසුව ඔහු විසින් අද දක්වා නිර්මාණය කල බොහොමයක් සිනෙමා නිර්මාණ අතිශය සාර්ථකත්වයට පත් විය. War Horse(2011), Bridge of Spies (2015), The BFG (2016), The Post (2017), Ready Player One (2018), West Side Story (2021) ඒ අතරින්,  කිහිපයකි. 
</p><p class='has-text-justified'>ඇකඩමි(ඔස්කාර්) සම්මාන 03ක්, බ්‍රිතාන්‍ය චිත්‍රපටි සම්මාන 02ක්, එමී සම්මාන 12ක් සහ ගෝල්ඩන් ග්ලෝබ් සම්මාන 07ක් ඇතුළුව ප්‍රධාන පෙළේ සම්මාන 152ක් ලබා ඇති මෙම අසහාය අධ්‍යක්ෂකවරයා, 2015 වසරේදී, ශ්‍රේෂ්ටත්වය වෙනුවෙන් පිරිනමන, ජනාධිපති පදක්කම බැරැක් ඔබාමා ජනපති අතින් ලබා ගත්තේය. 
</p><p class='has-text-justified'>චිත්‍රපට 150කට අධික සංඛ්‍යාවක් නිර්මාණය කර ඇති ස්ටීවන් ස්පීල්බර්ග්ගේ වත්කම, ෆොර්බ්ස් සඟරාවට අනුව ඇමෙරිකානු ඩොලර් බිලියන 3.7ක් පමණ වන අතර ඔහු හොලිවුඩයේ අතිශය සාර්ථකම අධ්‍යක්‍ෂකවරයා බව අවිවාදයෙන්ම පිළිගැනේ.   </p><div class='columns'><div class='column is-6'><figure><img src='./images/biography/12.jpg'><figcaption>Lincoln චිත්‍රපටයේ දර්ශනයක් </figcaption></figure><figure><img src='./images/biography/4.jpg'><figcaption>අමිස්ටඩ් - Amistad චිත්‍රපටියේ රූගත කිරීම් අතරතුර</figcaption></figure></div><div class='column is-6'><figure><img src='./images/biography/15.jpg'><figcaption>ශ්‍රේෂ්ටත්වය වෙනුවෙන් පිරිනමන, ජනාධිපති පදක්කම බැරැක් ඔබාමා ජනපති අතින් ලබා ගත් අවස්ථාව </figcaption></figure><figure><img src='./images/biography/11.jpg'><figcaption>Indiana Jones and the Kingdom of the Crystal Skull චිත්‍රපටියේ, හැරිසන් ෆෝඩ් සමඟින් සීන් කොනෙරි (සුප්‍රසිද්ධ ජේම්ස් බොන්ඩ් නළු) </figcaption></figure></div></div><?php require_once '../../template/footer.php'; ?>