<?php require_once '../../template/header.php'; ?><script>document.title = 'දැනුමිණ | ඔබ දන්නවාද?';document.querySelector('[data-class=heading]').textContent = 'කුහුඹුවන් එකිනෙකා හමුවූ විට කථා කරන්නේ මොනවාද?';document.querySelector('.prev-article-btn').lastElementChild.innerText = 'අද වැනි දවසක';document.querySelector('.next-article-btn').firstElementChild.innerText = 'කියන්න දිනන්න';document.querySelector('.prev-article-btn').setAttribute('href','./today.php');document.querySelector('.next-article-btn').setAttribute('href','../../quiz.php');</script><div class='columns'><div class='column is-5'><figure><img src='./images/doyouknow/1.jpg'><figcaption>ඔබ දැක ඇති කුහුඹු හමුව</figcaption></figure></div><div class='column is-7'><p class='has-text-justified'>ලොව මෙතෙක් සොයාගෙන ඇති කුහුඹු විශේෂ 12,000ක් පමණ වන බව ඔබ දන්නවාද?</p><p class='has-text-justified'>කුහුඹුවෙකුට තම සිරුරේ බර මෙන් විසි ගුණයක පමණ බරක් එසවිය හැකි බව ඔබ දැන සිටියාද?</p><p class='has-text-justified'>කුහුඹු කොලනියක කුහුඹු වර්ග තුනක් සිටී. ඒ, රැජිණ, පිරිමි කුහුඹුවන් සහ ගැහැණු ශ්‍රමිකයින් ලෙසයි.
කුහුඹු රැජිණියකට වසර ගණනක් ජීවත් විය හැකි අතර පැටවුන් මිලියන ගණනක් බිත්තර මඟින් බිහිකරයි.
පිරිමි කූඹීන්ගේ රාජකාරිය රැජිණට බිත්තර දැමීමට සහය වීමයි. ඉන් පසුව පිරිමි කූඹීන් ඉක්මණින් මිය යයි. මෙම රැජිණියන් හා පිරිමි කූඹීන් පමණක් පිහාටු දරයි.
</p></div></div><p class='has-text-justified'>රැජිණක් වැඩි වියට පත් වීමෙන් පසුව ඇගේ ඉතිරි ජීවිත කාලයම බිත්තර දමමින් ගත කරයි.
කුහුඹු කොලනියක රැජිණිය මියගිය පසුව මාස කිහිපයකින් එම කොලනිය විනාශ වී යයි.
</p><div class='columns'><div class='column is-4'><figure><img src='./images/doyouknow/2a.jpg'><figcaption>කුහුඹු කොලනියක් පොළව මතුපිට සිට අභ්‍යන්තරයට මිනිසෙකුගේ උසටත් වඩා වැඩි උසකින් ව්‍යාප්තවී තිබිය හැකිය. </figcaption></figure></div><div class='column is-4'><figure><img src='./images/doyouknow/2b.jpg'><figcaption></figcaption></figure></div><div class='column is-4'><p class='has-text-justified'>පිරිමි කුහුඹුවන් අතරින් පිරිසක් සෙබළුන් වේ. ඔවුන් කොලනිය ආරක්ෂා කිරීම, ආහාර රැස් කිරීම හෝ විනාශ කිරීම සිදු කරති. එමෙන්ම වෙනත් කොලනි ආක්‍රමණය කරමින් ආහාර සහ බිත්තර රැගෙන යාමද සිදු කරති.
</p><p class='has-text-justified'>එම බිත්තර වලින් කුහුඹුවන් ඇතිවුණු පසු උන්ව තම කොලනියේ මෙහෙකාර සේවයේ යොදවති. මෙම මෙහෙකාර කූඹීන් බිත්තර සහ කුහුඹු පැටවුන් රක බල ගැනීම, ආහාර රැස් කිරීම සහ කොලනිය ගොඩනැගීම වැනි කාර්යයන්ට යොදා ගැනේ.
</p><p class='has-text-justified'>මෙලෙස කුහුඹුවන් ලක්ෂ සංඛ්‍යාවක් සිටින සංකීර්ණ කුහුඹු කොලනියක එකිනෙකා අතර සම්බන්ධ වීමට සන්නිවේදන ක්‍රම තිබිය යුතුමය. </p></div></div><p class='has-text-justified'>ආහාර ඇති තැන් දැන්වීමට, සතුරු ප්‍රහාර දැන්වීමට මෙම සන්නිවේදනයන් අවශ්‍යවේ. ස්වභාවයෙන්ම ශබ්ද නැගීමේ හැකියාවන් නොමැති කූඹීන් මෙය සිදු කරන්නේ කෙසේද? ඔබ දන්නවාද?</p><div class='columns'><div class='column is-7'><p class='has-text-justified'>කුහුඹු රැළියක එකිනෙකා ඉදිරියට හමුවන කූඹීන් අතර සුලභම සන්නිවේදන ක්‍රමය වන්නේ පෙරමෝන නම්වන සුවඳවත් රසායනික ද්‍රව්‍ය ආඝ්‍රාණය කරමින් සිදු කරන සන්නිවේදනයයි.
</p><p class='has-text-justified'>එක කුහුඹියෙකුගේ ඉදිරි පාදවල තැවරුණු මෙම පෙරමෝන අනෙක් කුහුඹියාගේ හිසෙහි ඇති ඇන්ටෙනා මගින් හඳුනාගන්නා අතර එමඟින් ඔහුට හමුවුණු ආහාර සහ ඒවා හමුවුණු තැන් පිළිබඳ සන්නිවේදනය කරගනිති.
</p><p class='has-text-justified'>මෙලෙස මුහුණට මුහුණ හමුවන කූඹීන් අතර ට්‍රොෆලැක්සිස්  (Trophallaxis) නමින් වන මුඛයෙන් මුඛයට ආහාර හුවමාරු කරගන්නා සන්නිවේදන ක්‍රමයක්ද විද්‍යාඥයන් විසින් සොයාගෙන ඇත.
</p></div><div class='column is-5'><figure><img src='./images/doyouknow/5.jpg'><figcaption>සතුරු ආක්‍රමණයකදී හෝ ව්‍යසනයකදී කුහුඹුවන් තම කොලනියේ බිත්තර සියල්ල රැගෙන පලායති.</figcaption></figure></div></div><div class='columns'><div class='column is-4'><figure><img src='./images/doyouknow/6.jpg'><figcaption>හනිපොට් ඈන්ට් (HoneyPot Ants) නම්වන කුහුඹු වර්ගය ඇතැම් කොලනි වල සිටිමින් ඔවුන්ගේ සිරුරු කොටස්වල ආහාර ගබඩා කරති.</figcaption></figure><figure><img src='./images/doyouknow/6b.jpg'><figcaption>එම ගබඩාවන් ආහාර හිඟ ශීත කාලයට ඔවුන් අනෙකුත් කුහුඹුවන් සමඟ බෙදාහදා ගනිති.</figcaption></figure></div><div class='column is-4'><figure><img src='./images/doyouknow/8.jpg'><figcaption>දුඹුරු කුහුඹු රැජිණක් බිත්තර දමමින් </figcaption></figure><figure><img src='./images/doyouknow/4.jpg'><figcaption>කුහුඹු රැජින සහ ඇගේ ආරක්ෂකයින් </figcaption></figure><figure><img src='./images/doyouknow/9.jpg'><figcaption>ආහාර කැබැල්ලක් වටා එක්වුණු කුඹීන් </figcaption></figure></div><div class='column is-4'><figure><img src='./images/doyouknow/3.jpg'><figcaption>රතු කුහුඹු ආක්‍රමණිකයින්. කුහුඹු සටනක් අවසන් වන්නේ පරාජිතයාට මරණය ගෙන දෙමිනි.</figcaption></figure><figure><img src='./images/doyouknow/7.jpg'><figcaption>ට්‍රොෆලැක්සිස්  (Trophallaxis)</figcaption></figure></div></div><?php require_once '../../template/footer.php'; ?>
