<?php require_once '../../template/header.php'; ?><script>document.title = 'දැනුමිණ | ලොව වටා තතු';document.querySelector('[data-class=heading]').textContent = 'ලොව පුරා පුදුම හිතෙන නව වසර උදාව සැමරුම් ';document.querySelector('.prev-article-btn').lastElementChild.innerText = 'කියන්න දිනන්න';document.querySelector('.next-article-btn').firstElementChild.innerText = 'ක්‍රීඩා';document.querySelector('.prev-article-btn').setAttribute('href','../../quiz.php');document.querySelector('.next-article-btn').setAttribute('href','./sports.php');</script><div class='columns'><div class='column is-6'><figure><img  src='./images/world/27 (2).jpg' loading='lazy'><figcaption>සිඩ්නි වරායට ඉහළින් ගිනිකෙළි සංදර්ශන දිස්වූ අයුරු - ඔස්ට්‍රේලියාව </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/27 (9).jpg' loading='lazy'><figcaption>වසංගත තත්වය හේතුවෙන් ජනශුන්‍ය වූ රුසියාවේ මොස්කව් නුවර  දෙව් මැදුර, ක්‍රෙම්ලීනය සහ රතු චතුරශ්‍රයට ඉහළින් දිස්වන ගිනිකෙළි සංදර්ශන </figcaption></figure></div></div><p class='has-text-justified'>නව වසර උදාව ලොව පුරා අතිශය උත්කර්ෂවත් ලෙස සමරන්නකි. ලොව පුරා විවිධ රටවල මෙම සැමරුම් විශේෂිත අයුරින් සිදුවේ. මේ ඉන් පුදුම හිතෙන සැමරුම් කිහිපයකි.
</p><h6>ඇමෙරිකාව</h6><p class='has-text-justified'>විවිධ සංස්කෘතීන් එකතුවකින් හෙබි ඇමෙරිකා එක්සත් ජනපදය තම නව වසරේ උදාව සමරනු ලබන්නේ නිව්යෝක් නගරයේ ටයිම්ස් චතුරශ්‍රයේදී විශාල LED පැනල වලින් ආලෝකමත් වුණු බෝලයක් ස්වයංක්‍රීයව බිමට හෙළීමෙනි.
නව වසර උදාවට මිනිත්තුවක් තිබියදී ඇරඹෙන සැමරුමේදී මෙම වර්ණවත් අලෝකිත බෝලය විශේෂයෙන් සාදන ලද කණුවක් මතින් පහළට හෙළයි.
1907 වසරේදී ආරම්භ වුණු මෙම විශේෂිත සැමරුම සියවසකට වඩා වැඩි කාලයක් පුරා වාර්ෂිකව සිදුවන්නකි. මෙය නැරඹීමට හා විනෝද වීමට මිලියනයකට වැඩි ජනතාවක් සෑම වසරක දෙසැම්බර් 31 වනදා ටයිම්ස් චතුරශ්‍රයට එක්රොක් වෙති.
</p><div class='columns'><div class='column is-4'><figure><img  src='./images/world/2.jpg' loading='lazy'><figcaption>2013 නව වසර ඇරඹුම සැමරුමට ටයිම්ස් චතුරශ්‍රයට රැස්වුණු ජනකාය </figcaption></figure></div><div class='column is-4'><figure><img  src='./images/world/3.jpg' loading='lazy'><figcaption>2007 වසරේ ටයිම්ස් චතුරශ්‍රයෙහි බෝලය බිම හෙලීමට එය ක්‍රියාත්මක කිරීමට සහභාගිවූ ඇමෙරිකානු හමුදා කණ්ඩායමක් </figcaption></figure></div><div class='column is-4'><figure><img  src='./images/world/1.jpg' loading='lazy'><figcaption>LED පැනල වලින් අලෝකිත වූ බෝලය කණුව මත පිහිටුවා තිබේ.</figcaption></figure></div></div><h6>ස්කොට්ලන්තය </h6><div class='columns'><div class='column is-7'><p class='has-text-justified'>ස්කොට්ලන්තය නව වසර උදාව සමරනු ලබන්නේ අතිශය උත්කර්ෂවත් වූ විනෝද සාද වලිනි. ස්කොට් වචනයක් වූ හොග්මනේ ( Hogmanay ) ඔවුන් නව වසරට පෙර නව අවුරුදු සැන්දෑවට කියන නමයි.
එඩින්බර්ග් බලකොටුව වටා වීදි පුරා සාද පවත්වමින්,නටමින්, ටෝච් ලාම්පු එළි හා ගිණිකෙළි සැණෙකෙළි වලින් ආලෝකමත් වූ මේ සැමරුම් වලට අති විශාල ජනකායක් සහභාගී වේ.
</p><p class='has-text-justified'>ස්කොට්ලන්ත නව වසර සැමරීමේ සම්ප්‍රදායන් අතර, නව වසර උදාවේ නිවසට මුලින්ම එන පුද්ගලයා තෑගි රැගෙන ඒම සිදුවේ.
සම්ප්‍රදායක් ලෙස ඔවුන් ඥාතීන් සහ යහළුවන්ගේ නිවෙස් වලට මෙලෙස සම්ප්‍රදායික තෑග්ග ලෙස ගෙන යන්නේ වයින් බෝතලයක් සහ ස්කොට්ලන්ත කළු පාන් ගෙඩියකි.  මෙම සම්ප්‍රදාය ඔවුන් පළමු පා තැබීම ( first-footing ) ලෙස හඳුන්වයි.
</p></div><div class='column is-5'><figure><img  src='./images/world/5.jpg' loading='lazy'><figcaption>එඩින්බර්ග් බලකොටුවට ඉහළින් පෙනෙන ගිණිකෙළි සංදර්ශන </figcaption></figure></div></div><div class='columns'><div class='column is-6'><figure><img  src='./images/world/4.jpg' loading='lazy'><figcaption>එඩින්බර්ග් නුවර වීදි පුරා නව වසර සැමරුම් </figcaption></figure><figure><img  src='./images/world/6.png' loading='lazy'><figcaption>වීදි පුරා ලාම්පු හා පහන් එළි පාගමන් යන පිරිස</figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/7.jpeg' loading='lazy'><figcaption>සාද පවත්වමින් සීලිද් නර්තනයේ යෙදෙන ස්කොට්ලන්ත වැසියන් </figcaption></figure><figure><img  src='./images/world/8.jpg' loading='lazy'><figcaption>ස්කොට්ලන්තයට අවේණික ආහාරයක්වූ කළු පාන්  </figcaption></figure></div></div><h6>ස්පාඤ්ඤය</h6><p class='has-text-justified'>ස්පාඤ්ඤ  ජාතිකයින් නව වසර උදව සමරන්නේ ඔවුන්ට ආවේනිකවූ විශේෂිත ක්‍රමයකිනි. ස්පාඤ්ඤ  කොළ මිදි ගෙඩි 12ක් වරකට එක බැගින් මුවට දමා ගනිමින් ෂැම්පේන් පානය කරමින් 31 රෑ මධ්‍යම රාත්‍රිය ගත කිරීම ඔවුන්ගේ  සිරිතයි.
මෙලෙස මිදි ගෙඩියක් ගිලින සෑම වරකම ඔවුන් නව ප්‍රාර්ථනයක් සිදු කරති. සියවස් ගණනාවක් පැවතුණු මෙම චාරිත්‍රය සිදු කිරීම නව වසරේ මාස 12ටම වාසනාව ගෙනදෙන බව ඔවුන්ගේ විශ්වාසයයි.
මිදී ගෙඩි 12න් සංකේතවත් කරන්නේ නව වසරේ මාස 12යි. </p><div class='columns'><div class='column is-6'><figure><img  src='./images/world/9a.jpg' loading='lazy'><figcaption>ස්පාඤ්ඤ  කොළ මිදි චාරිත්‍රය හා ෂැම්පේන් </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/10.jpg' loading='lazy'><figcaption>නව වසර උදාව සැමරුමට රියල් මැඩ්රිඩ් නුවරට රැස්වුණු අතිවිශාල ජනකාය </figcaption></figure></div></div><h6>බ්‍රසීලය </h6><p class='has-text-justified'>බ්‍රසීල වැසියන්ගේ නව වසර උදාව සැමරුම  අංගයන් කිහිපයකින් සමන්විතවේ. සුදු පැහැති ඇඳුමින් සැරසුණු බ්‍රසීල වැසියන් යෙමෙන්ජා නමින් ඔවුන් හඳුන්වන මුහුදට අධිපති දෙවඟනට මල් කළඹ පූජා කරති.
වෙරළබඩ ප්‍රදේශවල සිටින ජනතාව මුහුදු රැළි හතක් පැනීමෙන්, පනින හැම වරකටම නව ප්‍රාර්ථනයක් සිදු කරමින් එමඟින් නව වසර වාසනාව ගෙනදෙන බව හා බාධක බිඳ හෙළීමේ හැකියාව ලැබෙන බව විශ්වාස කරති.
එමෙන්ම 31 රෑ මධ්‍යම රාත්‍රිය එළැඹුණු විටම රාත්‍රී ආහාරය ගැනීමට පෙර නව වසරේ ඔවුන්ගේ මුල්ම ආහාරය ජනප්‍රිය බ්‍රසීල බෝංචි සුප් පානයකි. බෝංචි, ධනය හා වාසනාව ආකර්ෂණය කරවන බව ඔවුන්ගේ විශ්වාසයයි.
</p><div class='columns'><div class='column is-6'><figure><img  src='./images/world/11.jpg' loading='lazy'><figcaption>සුදු පැහැති ඇඳුමින් නව වසර උදාව සැමරුමට රියෝ ද ජැනයිරෝ නුවරට රැස්වුණු බ්‍රසීල ජනතාව </figcaption></figure><figure><img  src='./images/world/13.jpg' loading='lazy'><figcaption> මුහුදු රැළි හතක් පැනීම වෙරළබඩ වෙසෙන බ්‍රසීල වැසියන්ගේ ජනප්‍රියතම නව වසර සැමරුම් අංගයකි </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/12.jpg' loading='lazy'><figcaption>යෙමෙන්ජා දෙවඟනට මල් කළඹ පූජා කිරීම </figcaption></figure><figure><img  src='./images/world/14.jpg' loading='lazy'><figcaption>බ්‍රසීල බෝංචි සුප් පානය නව වසරේ ඔවුන්ගේ මුල්ම ආහාරයයි.</figcaption></figure></div></div><div class='columns'><div class='column is-7'><h6>කොලොම්බියාව </h6><p class='has-text-justified'>කොලොම්බියානුවන් නව වසර උදාව සමරන්නේ වෙනස්ම ආකාරයේ සිරිත් විරිත් කිහිපයකිනි. 31 රෑ සැන්දෑවේ කොලොම්බියානුවන්  නව වසර සැමරීමට නිවෙස් වලින් පිටත් වන්නේ සුට් කේසයක් අතේ ඇතිවය.
එමඟින් නව වසර පුරාවට විනෝද ගමන් බිමන්, නව අත්දැකීම් ලැබෙන බව ඔවුන්ගේ විශ්වාසයයි.
</p><p class='has-text-justified'>එමෙන්ම ඔවුන්ගේ කලිසම් සාක්කු බෝංචි ඇටවලින් පුරවාගැනීමද විශේෂිතය. එමඟින් නව වසරේ සාර්ථකත්වය ඔවුන් අපේක්ෂා කරති.
පිටුපස සාක්කුවල මුදල් නෝට්ටුවක් රඳවාගෙන ගමන් කරන ඔවුන් ඉන් නව වසර පුරා මිල මුදල් අගහිඟකමින් තොරවූ සවුභාග්‍ය අපේක්ෂා කරති.
</p><figure><img  src='./images/world/17.jpg' loading='lazy'><figcaption>කොලොම්බියානු  නව වසර උදාවේ සම්ප්‍රදායික කෑම මේසය</figcaption></figure></div><div class='column is-5'><figure><img  src='./images/world/15b.jpg' loading='lazy'><figcaption>සූට් කේස් අතැතිව ගමන් කරන කොලොම්බියානුවන් </figcaption></figure><figure><img  src='./images/world/16.jpg' loading='lazy'><figcaption>කහ වර්ණයට මුලිකත්වය දෙමින්, කහ ඇඳුම්, කහ පැහැති සැරසිළි, කොලොම්බියානු  නව වසර සැමරුමේ විශේෂ අංගයකි.</figcaption></figure></div></div><h6>ඉතාලිය </h6><p class='has-text-justified'>උදාවන නව වසරට ආයුබෝවන් කියමින් නිවසේ පැරණි ගෘහ භාණ්ඩ ජනේල වලින් පිටතට වීසි කරන අරුම පුදුම සිරිතක් ඉතාලියේ පවතී.
එමඟින් ඔවුන් අපේක්ෂා කරන්නේ ඉකුත් වසරේ අමිහිරි මතකයන් ඉවත්කර නව වසර වාසනාවන්ත එකක් කරගැනීමයි.
මෙය විශේෂයෙන් දක්නට ලැබෙන්නේ ඉතාලියේ නේපල්ස් නගරයේයි. නව වසර එළැඹීමත් සමඟ නේපල්ස් නගරයේ වීදි දෙපස පැරණි ගෘහ භාණ්ඩ වලින් පිරී යයි. </p><div class='columns'><div class='column is-6'><figure><img  src='./images/world/18.jpeg' loading='lazy'><figcaption>රෝමයේ කොලෝසියමට ඉහළින් ගිණිකෙලි සංදර්ශන </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/19.jpg' loading='lazy'><figcaption></figcaption></figure></div></div><h6>ඩෙන්මාර්කය </h6><p class='has-text-justified'>නිවසේ පිඟන් කෝප්ප බිම හෙළමින් කරන අරුම පුදුම නව වසර උදාවේ චාරිත්‍රයක් ඔබ අසා තිබේද? ඒ ඩෙන්මාර්කයේයි.
තම අසල්වැසියාගේ නිවාස ඉදිරිපිට පිඟන් කෝප්ප බිම හෙලමින් විනෝද වීම ඔවුන්ගේ මෙම සිරිතයි. එමඟින් ඔවුන් නව වසරට සුභ පැතීම සිදු කරයි.
</p><div class='columns'><div class='column is-6'><figure><img  src='./images/world/21b.jpg' loading='lazy'><figcaption>ඩෙන්මාර්කයේ, කෝපන්හේගන් නුවර නව වසර සැමරුම් </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/21.jpg' loading='lazy'><figcaption>නිවෙස් ඉදිරිපිට පිඟන් බිඳ හෙළීම ඩෙන්මාර්ක් වැසියන් නව වසරට සුභ පතන ක්‍රමයයි.</figcaption></figure></div></div><div class='columns'><div class='column is-8'><h6>ඉක්වදෝරය</h6><p class='has-text-justified'>ඉක්වදෝර වැසියන්ගේ නව වසර සැමරුම් චාරිත්‍රය පුදුම හිතෙන එකකි. මෙම අරුම පුදුම නව වසර සැමරුමේදී චිත්‍රපටවල හා කාටුන්වල එන චරිත හෝ ඇතැම් කුප්‍රකට යැයි සැලකෙන චරිත, ලී, කඩදාසි හා රෙදි වලින් සාදා සියල්ලන් එක්වී පුළුස්සා දැමීම සිදු කරති.
</p><p class='has-text-justified'>එමෙන්ම ඇතැම් තරුණයින් එම ගිනිදැල් මතට වාර කිහිපයක් පැනීමද සිදු කරති. එමඟින් ඉකුත් වසරේ නරක, අමිහිරි සිදුවීම් හා සිතුවිලි විනාශ වී නව වසර යහපත් එකක් වන බව ඉක්වදෝර වැසියන්ගේ විශ්වාසයයි.
</p></div><div class='column is-4'><figure><img  src='./images/world/24.jpg' loading='lazy'><figcaption>පුළුස්සා දැමීමට නිමවූ පිළිරුවක්</figcaption></figure></div></div><div class='columns'><div class='column is-6'><figure><img  src='./images/world/23.jpg' loading='lazy'><figcaption></figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/22.png' loading='lazy'><figcaption>ගිනි තැබීම් සහ ඒ මතට පනින තරුණයින් </figcaption></figure></div></div><h6>ජපානය</h6><p class='has-text-justified'>බෞද්ධ සිරිත් විරිත් වලින් පෝෂණය වුණු ජපානයේ නව වසර සැමරීමේ සිරිත ආගමික මුහුණුවරක් ගනී.
ජොයා නෝ කානේ (Joya  no kane) ලෙස හඳුන්වන මෙම චාරිත්‍රයේදී ජපන් වැසියන් 31 දා අවට බෞද්ධ පන්සල් වලට රැස් වෙමින් පන්සලේ විශාලතම ඝණ්ටාරය 107 වතාවක් නාද කරති.
මධ්‍යම රාත්‍රිය එළඹී නව වසර උදාවූ පසු නැවත එක් වතාවක් නාද කරමින් චාරිත්‍රය අවසන් කරති. මෙමඟින් සියළු දුකට හේතුවන කරුණු නැතිවී නව වසර ආලෝකමත් වන බව ඔවුන්ගේ ඇදහීමයි. </p><div class='columns'><div class='column is-5'><figure><img  src='./images/world/27 (4).jpg'><figcaption>නව වසරට ආශීර්වාද පතමින් ජපානයේ දකුණු ටෝකියෝවේ, කමකුරා නගරයේ පිහිටි හසෙදෙරා බෞද්ධ විහාරයේ ඉටිපන්දම් දැල්වූ අයුරු </figcaption></figure></div><div class='column is-7'><figure><img  src='./images/world/25.jpeg' loading='lazy'><figcaption>(ජොයා නෝ කානේ) පන්සලේ විශාල ඝණ්ටාරය නද කරන භික්ෂුන් සහ රැස්ව සිටින ජපන් වැසියන් </figcaption></figure></div></div><h6>පිලිපීනය</h6><p class='has-text-justified'>පිලිපීනය නව වසර සැමරීමේදී සැමවිටම මුල්තැන දෙන්නේ රවුම්, වෘත්තාකාර දේ වලටයි. ඔවුන් මෙම විශේෂිත දිනයේ අඳින  ඇඳුම් සම්ප්‍රදායික පොල්කා ඩොට්ස් වලින් විචිත්‍ර වූ ඇඳුම්ය.
රවුම් හැඩති පළතුරු වලින් කෑම මේස පිරී යයි. රවුම් කාසි වලින් ඔවුන් සාක්කු පුරවාගනී.
</p><div class='columns'><div class='column is-6'><figure><img  src='./images/world/26.jpg' loading='lazy'><figcaption>පිලිපීන ජාතිකයින්ගේ නව වසර සැමරුම්වල විවිධ ශබ්ද නැගීම් සුලභවේ  </figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/26b.jpg' loading='lazy'><figcaption>පොල්කා ඩොට්ස් වලින් විචිත්‍රවත් ඇඳුම් ආයිත්තම්</figcaption></figure></div></div><h6>2022 නව වසරේ උදාව ලොව පුරා විවිධ ස්ථානවල සැමරූ අයුරු </h6><div class='columns'><div class='column is-6'><figure><img  src='./images/world/27 (10).jpg' loading='lazy'><figcaption>චීනයේ චොංක්වින්ග් නුවර නව වසර පිළිගැනීමට ජනතාව රැස්ව සිටින අයුරු </figcaption></figure><figure><img  src='./images/world/27 (7).jpg' loading='lazy'><figcaption>දෙසැම්බර් 31 දින බැසයන හිරු ආලෝකයට නමස්කාර කරමින් ඉන්දියාවේ අම්රිත්සාර් හි රන් දෙවොල දේවාලය අසල ශුද්ධ වූ සරෝවර් නදියේ ජල ස්නානය කරන සීක් බැතිමතුන්</figcaption></figure></div><div class='column is-6'><figure><img  src='./images/world/27 (11).jpg' loading='lazy'><figcaption>තායිලන්තයේ බැංකොක් නුවර අලුත් අවුරුදු උදාවේ සමරන නැවත නැඟිටීමේ උත්සවයකදී මිනිසුන් මිනී පෙට්ටිවල වැතිර සිටිති. නව වසරේදී අකුසල කර්ම දුරුවී වාසනාවන්ත සෞඛ්‍ය සම්පන්න බව ලැබේවියැයි ඔවුන් විශ්වාස කරති.</figcaption></figure><figure><img  src='./images/world/27 (12).jpg' loading='lazy'><figcaption>ලන්ඩනයේ ශාන්ත පාවුළු දෙව්මැදුර සහ මිලේනියම් පාලමට ඉහළින් ආලෝක සංදර්ශනය නරඹන එංගලන්ත වැසියන්.</figcaption></figure></div></div><?php require_once '../../template/footer.php'; ?>
